apiVersion: v1
kind: ConfigMap
metadata:
  name: lakefs-config
data:
  LAKEFS_ACCESS_KEY_ID: <LAKEFS_ACCESS_KEY_ID>
  LAKEFS_SECRET_ACCESS_KEY: <LAKEFS_SECRET_ACCESS_KEY>
  LAKEFS_URL: http://<LAKEFS_HOST>:30800
  MINIO_URL: http://<MINIO_HOST>:30900
  MINIO_ACCESS_KEY: <MINIO_ACCESS_KEY>
  MINIO_SECRET_KEY: <MINIO_SECRET_KEY>
